apiVersion: apps/v1
kind: Deployment
metadata:
  name: rti-clouddiscoveryservice
spec:
  selector:
    matchLabels:
      run: rti-clouddiscoveryservice
  replicas: 3
  template:
    metadata:
      labels:
        run: rti-clouddiscoveryservice
    spec:
      containers:
      - name: rti-clouddiscoveryservice
        image: kyoungho/rti-clouddiscoveryservice
        volumeMounts:
          - name: license-volume
            mountPath: /app/license
        ports:
        - containerPort: 7400
          protocol: UDP
      volumes:
        - name: license-volume
          configMap:
            name: rti-license

