---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rtiperftest-pub"
  namespace: "default"
  labels:
    app: "rtiperftest-pub"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rtiperftest-pub"
  template:
    metadata:
      labels:
        app: "rtiperftest-pub"
    spec:
      containers:
      - name: "rtiperftest-pub"
        image: "kyoungho/rti-perftest-pub"
        env:
        - name: NDDS_DISCOVERY_PEERS
          value: rtps@rti-clouddiscoveryservice:7400
      nodeSelector:
        perftest: pub
